"""scripts/check_env.py: the environment-equals-lock check (plan P1-W1)."""

import shutil
import subprocess

import pytest

from tests.conftest import load_script

CE = load_script("check_env")

EXPORT = """# This file was autogenerated by uv
-e .
numpy==2.4.6 ; python_full_version < '3.12'
numpy==2.5.3 ; python_full_version >= '3.12'
torch==2.11.0 ; sys_platform == 'darwin'
torch==2.11.0+cu128 ; sys_platform == 'linux'
pyyaml==6.0.3
"""


def env(platform, python_full):
    return {
        "sys_platform": platform,
        "platform_machine": "arm64" if platform == "darwin" else "x86_64",
        "python_full_version": python_full,
        "python_version": ".".join(python_full.split(".")[:2]),
        "implementation_name": "cpython",
        "platform_system": "Darwin" if platform == "darwin" else "Linux",
        "os_name": "posix",
        "platform_python_implementation": "CPython",
        "platform_release": "",
        "platform_version": "",
        "implementation_version": python_full,
        "extra": "",
    }


def test_parse_export_skips_comments_and_the_project():
    reqs = CE.parse_export(EXPORT)
    assert [r.name for r in reqs] == ["numpy", "numpy", "torch", "torch", "pyyaml"]


def test_compare_installed_evaluates_markers_per_platform():
    reqs = CE.parse_export(EXPORT)
    linux = {"numpy": "2.4.6", "torch": "2.11.0+cu128", "pyyaml": "6.0.3"}
    assert CE.compare_installed(reqs, linux, env("linux", "3.11.16")) == ([], [])
    mac = {"numpy": "2.5.3", "torch": "2.11.0", "pyyaml": "6.0.3"}
    assert CE.compare_installed(reqs, mac, env("darwin", "3.12.4")) == ([], [])


def test_compare_installed_reports_drift_and_missing():
    reqs = CE.parse_export(EXPORT)
    mismatches, missing = CE.compare_installed(
        reqs, {"numpy": "2.4.5", "torch": "2.11.0"}, env("linux", "3.11.1")
    )
    assert any("numpy: installed 2.4.5, lock pins 2.4.6" in m for m in mismatches)
    assert any("torch: installed 2.11.0, lock pins 2.11.0+cu128" in m for m in mismatches)
    assert missing == ["pyyaml==6.0.3"]


def test_python_and_cuda_build_checks():
    assert CE.check_python("3.11", (3, 11, 16)) == []
    assert CE.check_python("3.11", (3, 12, 1)) != []
    assert CE.check_cuda_build("linux", "12.8") == []
    assert CE.check_cuda_build("linux", "13.0") != []
    assert CE.check_cuda_build("darwin", None) == []
    assert CE.check_cuda_build("win32", None) != []


def test_expected_python_reads_the_pin():
    assert CE.expected_python() == "3.11"


@pytest.mark.slow
def test_this_environment_passes():
    """The live venv equals the lock (skipped in fast mode; CI and --full run it)."""
    assert CE.main([]) == 0


def test_parse_export_ignores_ansi_colour():
    """CI run 36322586655: FORCE_COLOR=1 made uv colour its "# via" lines, and they failed to parse."""
    coloured = "absl-py==2.5.0\n\x1b[32m    # via tensorboard\x1b[39m\n\x1b[1mpyyaml==6.0.3\x1b[0m\n"
    assert [str(r) for r in CE.parse_export(coloured)] == ["absl-py==2.5.0", "pyyaml==6.0.3"]


def test_uv_export_asks_for_plain_output(monkeypatch):
    seen = {}

    def fake_run(cmd, **kw):
        seen["cmd"], seen["env"] = cmd, kw["env"]
        return subprocess.CompletedProcess(cmd, 0, stdout="", stderr="")

    monkeypatch.setenv("FORCE_COLOR", "1")
    monkeypatch.setattr(CE.subprocess, "run", fake_run)
    monkeypatch.setattr(CE.shutil, "which", lambda _: "/usr/bin/uv")
    monkeypatch.delenv("UV", raising=False)
    CE.uv_export()
    assert "--no-annotate" in seen["cmd"] and seen["cmd"][seen["cmd"].index("--color") + 1] == "never"
    assert "FORCE_COLOR" not in seen["env"] and seen["env"]["NO_COLOR"] == "1"


@pytest.mark.skipif(shutil.which("uv") is None, reason="uv not on PATH")
def test_live_export_parses_under_force_color(monkeypatch):
    """The CI condition, reproduced: the real uv, FORCE_COLOR=1, the real lock."""
    monkeypatch.setenv("FORCE_COLOR", "1")
    reqs = CE.parse_export(CE.uv_export())
    names = {r.name for r in reqs}
    assert {"torch", "numpy", "pytorch-lightning"} <= names
