"""Evaluation sets (plan P3-P, P3-Q): fetched, never trained on.

Retrieval: GerLeRB (statutes), GerDaLIR (case law). Question answering: LegalQuAD, GerLayQA. Each
module pairs pure ``parse_*`` functions (tested on fixtures) with ``fetch(limit)``; the CLI

    python -m lexhybrid.data.evalsets.gerlerb --limit 20

writes ``data/evalsets/<name>/`` (git-ignored) and ``data/manifests/evalset_<name>.jsonl``. None of
them produces a corpus ``Document``, so none can reach a training shard; GerLayQA is also
non-commercial research-only data, and GerLeRB's queries were generated by GPT-4.1 (R10).
"""
